name: GitHub Pages
on:
  push:
    branches: [main]
permissions: 
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 21
      - uses: actions/checkout@v4
      - run: |
          npm install
          node build.mjs gh-pages
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: www